### ISSUE TITLE
OD Matrix randomly drops one record

### ISSUE THREAD

**Issue by josephholler** [root676/QNEAT3#10]
I'm running QGIS version 3.2.1 and QNEAT3 version 1.0.1 on Windows 10.
I have noticed that OD Matrix from Layers algorithm always results in one fewer records than expected, and that the missing record is not always the same record.  For example, given an input of 8 destination points and 11 origin points, the resulting table has 87 records, where 88 are expected.
The algorithm dialogue says that the correct number of pairs (88) were processed. (Total number of OD-pairs processed: 88)
This cannot be an error in the lines, origins, or destinations, because the missing pair is not the same and thus the missing pair has been correctly calculated in other iterations of running the algorithm or with different subsets of the data.
I have not been able to determine a consistent pattern as to _which_ record is dropped.

Thanks for this useful plugin!

**Comment by root676** [comment]
Hi @josephholler,
I had a look into the issue - it was a wrong if statement. Could you please test the master version in this repo whether you still get the issue?
Thx!

**Comment by josephholler** [comment]
I saw your code fix and it makes sense.  The structure of if - else if -
would have dropped the 0th record and every 1000th record thereafter.
It was actually my students in an introductory GIS course who identified
the issue while they were working on a final exam.  I'm slammed with the
work of *grading* the exam now, and will try the new code as soon as I can.

**Comment by josephholler** [comment]
Yes, this fixed the error!  Many thanks.
