### ISSUE TITLE
Minimal example for "fastest" criterion

### ISSUE THREAD

**Issue by axlehner** [root676/QNEAT3#12]
Thank you for this nice plug-in.
One thing that is not obvious (even after having worked myself in QGIS with automating iterations of properters and different optimisation strategies) is what the network cost of the "fastest" algorithm actually reports. (for "shortest" it is clear, it is just the distance in metres)

I am working in EPSG:4326, entry and exit cost give the distance in metres to the network, but the actual network cost doesn't seem to be a time unit (it is not distance for sure). I played around with different distances and default speeds (and costs for each vertex) and could not figure it out. Could you describe in what units the cost do have to be specified (m/s? km/h?) and what the network_cost output actually resembles?

**Comment by root676** [comment]
Hi @axlehner, yes you are right - this is a thing that should be clearer from the algorithm helpstrings and documentation. 

The 'Fastest Path (time optimization)' strategy returns time-based cost values that are calculated using the speed values of the networks 'Speed Field' parameter and the 'Default Speed (km/h)' Parameter (this is the only hint on the unit that has to be used for the speed values). The default values for speed should be in **kilometers per hour (km/h)**. The resulting cost values (for network cost **and** entry and exit costs) are measured in **seconds** which pass by as you to traverse the fastest path given a set of speed values. Edges that don't have speed values assigned will automatically use the 'Default Speed (km/h)' value (defaults to 5km/h). This default speed also is the speed for entry and exit legs of the fastest path. I hope this provides some clarification.

**Comment by tomrod** [comment]
Agreed with the comment! Took me awhile to find this. Adding (km/h) or (crs units) would be helpful for both Topology and Speed.

Your implementation is wonderful and I am grateful for it.

**Comment by alaatorkey95** [comment]
@root676 what if I have used another attribute instead of "Speed" in the "Speed Field"..as if I am trying to use the fastest path optimization to quantify the routes based on another attribute than speed?

How will this affect the calculation of the network cost as well as entry and exit costs?
