### ISSUE TITLE
matplotlib install in MacOS

### ISSUE THREAD

**Issue by strozzascotte** [root676/QNEAT3#13]
Hi @root676 , I use your plugin in QGIS 3.6 on MacOS. 
I just want you to know that matplotlib can be easily installed in MacOS using the pip command provided by the QGIS3 installer with the following command:

`/Library/Frameworks/Python.framework/Versions/3.6/bin/pip3.6 install matplotlib`

Maybe you could add MacOS instructions to QNEAT3 webpage.

Thank you for this very useful tool.

**Comment by root676** [comment]
Sorry for the very late feedback. Thank you very much for the contribution of the installation instructions for macOS - I added them to the [QNEAT3-Installation page](https://root676.github.io/installation.html).
