### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by soli004** [root676/QNEAT3#15]
What can the problem be? Any hints where to look?
Error message below in log window..

[QNEAT3Network][calcIsoPoints] Added 12160000 Nodes to iso pointcloud...
[QNEAT3Network][calcIsoPoints] Added 12170000 Nodes to iso pointcloud...
[QNEAT3Network][calcIsoPoints] Added 12180000 Nodes to iso pointcloud...
[QNEAT3Network][calcIsoPoints] Added 12190000 Nodes to iso pointcloud...
[QNEAT3Algorithm] Calculating Iso-Interpolation-Raster using QGIS TIN-Interpolator...
[QNEAT3Algorithm] Calculating Iso-Polygons using numpy and matplotlib...
Traceback (most recent call last):
File "/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QNEAT3/algs/IsoAreaAsPolygonsFromPoint.py", line 249, in processAlgorithm
polygon_featurelist = net.calcIsoPolygons(max_dist, interval, output_path)
File "/Users/username/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/QNEAT3/Qneat3Framework.py", line 469, in calcIsoPolygons
band_in = ds_in.GetRasterBand(1)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

Execution failed after 2151.26 seconds

Loading resulting layers
Algorithm 'Iso-Area as Polygons (from Point)' finished

**Comment by root676** [comment]
Hi @soli004, it looks like the interpolation went wrong with your data. Do you get an output when you use the QNEAT3 interpolation algorithm or the pointcloud algorithms?
Any hints on your data (testdataset) would be helpful.

**Comment by soli004** [comment]
Hi, no there is zero output, it is strange though... works in other areas but not everywhere and it is the same map with same settings.
I use the "Iso-Area as Polygons (From Point) and it is a large network map (country).
I use MapInfo (tab)file as network file with a column of speed data where certain roads has "speed = 0" (bicycle roads) if that can be a problem but then it should not have worked in other areas. I use the time settings with 3600 sec (1 hour) and 300 sec as divider (5 min)

**Comment by soli004** [comment]
![PrintScreen 2019-05-12 kl  18 48 54](https://user-images.githubusercontent.com/5410735/57585311-ca7cfe00-74e6-11e9-9788-e318f96cf23c.jpg)

The two red dots on the map is areas where I get the errors, and this are not the only ones. Have no idea why it is not working, tried several times but no change in parameters settings... the purple polygons are from the result using QNEAT3

**Comment by root676** [comment]
So even the pointcloud algorithm doesn't return anything? In this case, I suppose that the problem comes from connection errors in the graph. I have experienced similar errors in areas, where the nearest edge to the point is not properly connected at either end node. Did you check that? (nice cartography btw) ;-)

**Comment by soli004** [comment]
Nope, nada return, I will try to move the coordinates for the start point to see if things change.
Yes thanks :-), I'm pleased with the style, image show 5, 10 and 15 minutes drive time and the analysts can activate up to 1 hour (with 5 and (after 30 min) 10 min increments) and see where things comes together with other start points. There is a batch solution but I'm missing the advance settings as I want to use the speed table... drive time is more expensive than counting kilometres.. To run thru 20 - 30 different starting points keeps me being alert to run the next and next and.... With the batch I could run it overnight and be done with it.. :)

**Comment by soli004** [comment]
Sorry did misunderstand your question, I answered for the polygon algorithm not the pointcloud algorithm . I did check the network for errors around the starting point, could not see any major, did some updates but still error when running polygons algorithm . I did recently test with pointcloud algorithm and the output result is not a success either, only the starting point (one point only) as final result. If you give me an email address I could send you part of the area that I have trouble with for you to have a look at if needed.... I'm stranded with this...

**Comment by root676** [comment]
This is a good idea! You can find my email adress in the source code headers of the python files in the repo.  For me, the error in the point algorithm hints at something on the graph building side... If you send me the files, I will have alook at it.

**Comment by soli004** [comment]
Files sent and with image of settings, thank you...

**Comment by root676** [comment]
Hi, I had a brief look at the data and saw that you added some zero values in the speed field. Altough I don't know the exact position of your starting points, I assume that it snaps to such a zero-speed-graph-edge which causes the analysis to stop right there because it is not allowed to drive at any velocity. After a quick check with disabled zero-speed-edges I was able to run all algorithms without errors. Could you check that too?

**Comment by soli004** [comment]
Thanks, yes you have the exact position and my settings in the image file that was sent as well. I was correct then as I was mentioning speed categories had zero value in the speed fields. This is road links for bicycles and so not allowed to drive there, that is why it is set to zero. So the only way is to remove the road links from the map or set a very low speed on this? I did set a value of 1 and that solve the problem

**Comment by JosephBenita** [comment]
Dear, 
i've got quite a similar error but solution develop here is not working. 

Here's the log: 
Traceback (most recent call last):
File "C:\Users/josep/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\algs\IsoAreaAsContoursFromPoint.py", line 250, in processAlgorithm
contour_featurelist = net.calcIsoContours(max_dist, interval, output_path)
File "C:\Users/josep/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\Qneat3Framework.py", line 411, in calcIsoContours
band_in = ds_in.GetRasterBand(1)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

Note that the pointcloud algorithm is properly working. 
I'm working with an OSM extraction using QuickOSM and downloading the road network of a city (I tried Bamako and then Dakar, same result).

**Comment by Kalyani-Khamgaonkar** [comment]
[QNEAT3Algorithm] Calculating Iso-Polygons using numpy and matplotlib...
Traceback (most recent call last):
File "C:\Users/kkham/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\algs\IsoAreaAsPolygonsFromLayer.py", line 255, in processAlgorithm
polygon_featurelist = net.calcIsoPolygons(max_dist, interval, output_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/kkham/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\Qneat3Framework.py", line 462, in calcIsoPolygons
ds_in = gdal.Open(interpolation_raster_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS34~1.10\apps\Python312\Lib\site-packages\osgeo\gdal.py", line 10666, in Open
return _gdal.Open(*args)
^^^^^^^^^^^^^^^^^
RuntimeError: C:/Users/kkham/AppData/Local/Temp/processing_cXZsEc/af4e34d8784f4cc89db734cde02dccca/OUTPUT_INTERPOLATION.tif: No such file or directory

Execution failed after 5.20 seconds

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/kkham/AppData/Local/Temp/processing_cXZsEc/af4e34d8784f4cc89db734cde02dccca/OUTPUT_INTERPOLATION.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.


I am consitently getting this error?
