### ISSUE TITLE
Unable to run python-qgis -m pip install matplotlib

### ISSUE THREAD

**Issue by sindile** [root676/QNEAT3#23]
Running python-qgis -m pip install matplotlib I get the following output "python-qgis: command not found"
This is even though python-qgis is installed apt-get install python-qgis on Ubuntu 19.10:
The following NEW packages will be installed python-qgis
0 to upgrade, 1 to newly install, 0 to remove and 2 not to upgrade.
Need to get 2,149 kB of archives.
After this operation, 2,234 kB of additional disk space will be used.
Get:1 https://qgis.org/debian eoan/main amd64 python-qgis all 1:3.10.0+31eoan [2,149 kB]
Fetched 2,149 kB in 4s (543 kB/s)        
Selecting previously unselected package python-qgis.
(Reading database ... 385265 files and directories currently installed.)
Preparing to unpack .../python-qgis_1%3a3.10.0+31eoan_all.deb ...
Unpacking python-qgis (1:3.10.0+31eoan) ...
Setting up python-qgis (1:3.10.0+31eoan) ...

**Comment by root676** [comment]
Try it once again with `python -m pip install matplotlib`.

**Comment by sindile** [comment]
Thanks, the command works.
