### ISSUE TITLE
OD Matrix from Layers as Lines (m:n) reports null when network is not used

### ISSUE THREAD

**Issue by alexberd** [root676/QNEAT3#24]
Hi @root676,

Thanks a lot for developing this awesome tool!

After reading carefully to understand how it works at the following pages..[1](https://root676.github.io/OdMatrixAlgs.html), [2](https://gis.stackexchange.com/questions/292519/distance-matrix-with-2-point-shapefiles-and-one-street-network/292537#292537)..I found that when using "fastest Path" Optimization Criterion and when the "From Point Layer" and the "To-Point Layer" are too close to each other, so that the network is not used for traveling, the calculated time of the values entry_cost, network_cost, exist_cost and total_cost are null.

Would it be possible in the above cases, algorithm to calculate the traveling time between starting and ending point and storing it to one of the costs parameters?

This will be very usefull for instance when few travel distances rely on the actual (physical time distances - using the default speeds) for trasportation rather than to the network.

Please let me know if the above make sense.
I look forward hearing from you!

Regards,
Alex

**Comment by root676** [comment]
Hi, I'm not quite sure if I understand your question correctly. What do you mean by from and to layers being "too close to each other". Are they identical? The network is always used for traveling unless the two layers are identical (why should there be a need of using the network or entering it?)
