### ISSUE TITLE
[Enhancement] report NULL or delete OD pairs with no routes

### ISSUE THREAD

**Issue by jecogeo** [root676/QNEAT3#26]
Dear @root676 , after [Issue 25](https://github.com/root676/QNEAT3/issues/25), the tool is working great. I just ran for more than a million O-D pairs and it is working like a charm. I'd like to reccomend an enhacement though: When no route is found for a given O-D pair, the last valid `total_cost` is taken, generating the false impression of distance. If someone is in a rush, it seems always went ok. When carefullly inspecting my +1M resulting table, I noticed several duplicated values in the `total_cost` column.  After comparing these duplicated values with the standard shortest path QGIS tool, I realized where those duplicated values came from.

As an improvement to avoid false impressions/conclusions to your users, I'd like to suggest to chain your tool with `Vector general` > `delete duplicates by attribute` or report NULL instead. Some outputs in the logs might be usefull too. This is just a suggestion and I understand if it doesn't fit your beforehand design, anyway.

Cheers

**Comment by root676** [comment]
Thanks for the feedback! This should definitely be handled by QNEAT3.

**Comment by apotapop** [comment]
Hi just to follow up on this, is there a solution that could help in removing these duplicated values? I am using the OD Matrix tool not only to calculate distance between points, but also to establish whether or not there is connectivity between specific pairs of points at all. The duplicated values give the false impression that pairs of points are connected when they are not, and it is impossible to determine which duplicate is the correct one to keep. Seems like this is a major problem for large datasets where manually checking whether or not two points are actually connected is impossible. Thanks!

**Comment by spatialthoughts** [comment]
+1 to fix this. This results in wrong results when trying to process the distance matrix.

**Comment by caaficus** [comment]
Dear @root676,

Is there any update on this issue? Or any alternative solution we can implement to deal with it? 

Thanks in advance for your support!

**Comment by root676** [comment]
@caaficus as you see I pushed a fix for this problem earlier this year to the repository. Unfortunately I have not yet been able to publish an update in the QGIS plugin repo due to ongoing work on QNEAT3. You can just download this github repository and replace the QNEAT3 folder in the QGIS plugin folder with this repo. Then it should work.

**Comment by caaficus** [comment]
@root676 It works! Thanks a lot!

**Comment by wdossett** [comment]
Hi @root676 , just checking if this bug has been fixed in the plugin, or should we still be updating from the repository?

**Comment by root676** [comment]
Implemented in 1.0.5
