### ISSUE TITLE
Allow for different origin and destination ID data types

### ISSUE THREAD

**Issue by josephholler** [root676/QNEAT3#31]
The OD Matrix algorithms currently force the destination unique ID to be the same data type as the origin unique ID. The documentation hints that these must be numeric, but text strings can be used.

I suggest that both IDs should use their original data types, similarly to the QGIS Distance Matrix algorithm.

**Comment by root676** [comment]
Thanks for adressing this in your PR! This is very useful and should be implemented!

**Comment by root676** [comment]
Implemented in 1.0.5
