### ISSUE TITLE
QNEAT3 Isochrone from Point Crash

### ISSUE THREAD

**Issue by leandrop0x** [root676/QNEAT3#38]
Encountered this error when running QNEAT3 for Isochrone Analysis... 

What could be the solution? 

[QNEAT3Algorithm] This is a QNEAT3 Algorithm: 'Iso-Area as Polygons (from Point)'
[QNEAT3Algorithm] Building Graph...
[QNEAT3Network][__init__] Setting up parameters
[QNEAT3Network][__init__] Setting up network direction parameters
[QNEAT3Network][__init__] Setting up analysis points
[QNEAT3Network][__init__] Setting analysis strategy: 0
[QNEAT3Network][__init__] Start tying analysis points to the graph and building it.
[QNEAT3Network][__init__] This is a compute intensive task and may take some time depending on network size
[QNEAT3Network][__init__] Start Time: :2020-10-08 17:00:02
[QNEAT3Network][__init__] Building...
Traceback (most recent call last):
File "C:/Users/Leandro Poco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\algs\IsoAreaAsPolygonsFromPoint.py", line 223, in processAlgorithm
net = Qneat3Network(network, input_coordinates, strategy, directionFieldName, forwardValue, backwardValue, bothValue, defaultDirection, analysisCrs, speedFieldName, defaultSpeed, tolerance, feedback)
File "C:/Users/LRP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\Qneat3Framework.py", line 130, in __init__
self.list_tiedPoints = self.director.makeGraph(self.builder, self.list_input_points, self.feedback)
Exception: unknown

Execution failed after 0.10 seconds

**Comment by root676** [comment]
I just gave some feedback in your related GIS.SE question. I'll be closing this because the error is related to QGIS classes that used by QNEAT3 but not maintained by QNEAT3.

**Comment by leandrop0x** [comment]
Thank you. Sorry - I'm a beginner and I don't understand what I could be doing wrong. I snapped the point of the graph that I wanted to use as the origin for the analysis. Is this what you are referring to in the GIS.SE comment you sent?
