### ISSUE TITLE
No output polygons or contours in QGIS 3.16.3 (OS X)

### ISSUE THREAD

**Issue by mvaneggermond** [root676/QNEAT3#42]
When running several QNEAT tools (Iso-Areas as Polygons (from Layer), or the Contour version., for instance) the only output is the intrapolation; it  The polygon layer is empty. 

The Iso-Areas as Pointcloud does output the point cloud. I have 3.16.3-Hannover installed on macOS 10.15. I can confirm that QNEAT works as expected in QGIS 3.14 on the same computer. 

When comparing the log between the two versions, it becomes apparent that in QGIS 3.14 QNEAT reaches this step: 

[QNEAT3Algorithm] Calculating Iso-Interpolation-Raster using QGIS TIN-Interpolator...
[QNEAT3Algorithm] Calculating Iso-Polygons using numpy and matplotlib...
[QNEAT3Network][calcIsoPolygons] calculating 500.0-level contours

Whereas in QGIS 3.16 it does not calculate the polygons:

[QNEAT3Algorithm] Calculating Iso-Interpolation-Raster using QGIS TIN-Interpolator...
[QNEAT3Algorithm] Calculating Iso-Polygons using numpy and matplotlib...
[QNEAT3Algorithm] Ending Algorithm

I am happy to send over the data, if that helps. Thanks for looking into this issue!

**Comment by mira78** [comment]
Having the same issue, both on QGIS 3.16 and 3.18.

**Comment by root676** [comment]
It seems there is an issue with your matplotlib installation on macOS. Unfortunately I have no machine to check this bug. Do the algorithms work on linux/windows for you?

**Comment by mira78** [comment]
Can't check linux/windows, unfortunately don't have a device. Tried to install/re-install matplotlib manually, including from various older python versions as well as separate matplotlib download and installation - but nothing helped. 
Any information/data/files I can provide to help?
