### ISSUE TITLE
Iso-Area Polygon tool results are 10 times bigger

### ISSUE THREAD

**Issue by guneshland** [root676/QNEAT3#47]
Version 1.0.4

I tested this tool (Iso-Area Polygon tool (from Point)) to calculate isochrones based on moving speed of the roads. The result surprised me: moving on streets with 60 km/h assigned speed takes as much time as walking on foot. I tried to run Iso-Area as contours with exactly same parameters, then I saw adequate results. I noticed that previous results showed 10 times bigger time than on the second try when isolines were same, but 10 times sparser. I can evade this issue by dividing the result by 10 or multiplying the speed by 10, but this can confuse someone. I haven't tried yet other tools. I hope you will fix that issue. 
Pictures illustrate the mistake: red lines indicate Polygon tool, black lines indicate contours tool
![Screenshot 2021-04-23 232113](https://user-images.githubusercontent.com/83093764/115925957-ad028e00-a48a-11eb-8122-fb513dcfbdd7.png)

**Comment by root676** [comment]
Thank you for reporting this. Unfortunately I am not able to reproduce this error. I would advise you to check your data and parameters again. The reason why this has to be a problem on the data/parameter side is, that both, Contours as well as Isochrones rely the same method in the background.
