### ISSUE TITLE
OD matrix extrudes lines and returns wrong costs

### ISSUE THREAD

**Issue by andremano** [root676/QNEAT3#50]
Using QNEAT3 under QGIS 3.18.3 and I am having problems to generate the outputs with OD matrices, specifically the Layer to Layer tool. The restults are over extended lines and loonking at the costs value (using shortest distance), they don't seem to make much sense either (assuming they are in meters). Screenshot below.

![image](https://user-images.githubusercontent.com/6665872/122079089-5fa4fc00-cdfd-11eb-94ee-6794834dd9dc.png)

The other tools work fine and give sound results. I am attaching sample data just in case it might be something with the input data.

Data: https://filesender.surf.nl/?s=download&token=94b5f1c0-3e90-4533-8a62-9cd9dfcdb9e6

**Comment by josephholler** [comment]
Something is strange with your CRSs: `bus_stop` has a different `EPSG` code even though it appears to also use UTM Zone 32N.  The EPSG code matches to zone 36N, and the distance calculator in QGIS is probably just using the EPSG code.  Is the other end of all of your OD lines in UTM zone 36N?

**Comment by andremano** [comment]
Ah! That was it! Thanks @josephholler for looking into it! I repairde the CRS and now it works as expected. Closing this issue
