### ISSUE TITLE
Failing at line 229 - IsoPolygonsFromLayer.py & QNeat3Framework line 130

### ISSUE THREAD

**Issue by civil142** [root676/QNEAT3#51]
QGIS version: 3.20.2-Odense
QGIS code revision: 9f59a156
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.1
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.0, July 1st, 2021
PDAL version: 2.3.0 (git-version: eac774)
Processing algorithm…
Algorithm 'Iso-Area as Polygons (from Layer)' starting…
Input parameters:
{ 'CELL_SIZE' : 10, 'DEFAULT_DIRECTION' : 2, 'DEFAULT_SPEED' : 5, 'DIRECTION_FIELD' : '', 'ENTRY_COST_CALCULATION_METHOD' : 0, 'ID_FIELD' : 'id', 'INPUT' : 'Z:/KEI/Projects/054 -Bennerley Viaduct/Walking network.shp', 'INTERVAL' : 500, 'MAX_DIST' : 2000, 'OUTPUT_INTERPOLATION' : 'TEMPORARY_OUTPUT', 'OUTPUT_POLYGONS' : 'TEMPORARY_OUTPUT', 'SPEED_FIELD' : '', 'START_POINTS' : 'Z:/KEI/Projects/054 -Bennerley Viaduct/Site location.shp', 'STRATEGY' : 0, 'TOLERANCE' : 0, 'VALUE_BACKWARD' : '', 'VALUE_BOTH' : '', 'VALUE_FORWARD' : '' }

[QNEAT3Algorithm] This is a QNEAT3 Algorithm: 'Iso-Area as Polygons (from Layer)'
[QNEAT3Algorithm] Building Graph...
[QNEAT3Network][__init__] Setting up parameters
[QNEAT3Network][__init__] Setting up network direction parameters
[QNEAT3Network][__init__] Setting up analysis points
[QNEAT3Network][__init__] Setting analysis strategy: 0
[QNEAT3Network][__init__] Start tying analysis points to the graph and building it.
[QNEAT3Network][__init__] This is a compute intensive task and may take some time depending on network size
[QNEAT3Network][__init__] Start Time: :2021-09-22 09:05:19
[QNEAT3Network][__init__] Building...
Traceback (most recent call last):
File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\algs\IsoAreaAsPolygonsFromLayer.py", line 229, in processAlgorithm
net = Qneat3Network(network, input_coordinates, strategy, directionFieldName, forwardValue, backwardValue, bothValue, defaultDirection, analysisCrs, speedFieldName, defaultSpeed, tolerance, feedback)
File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\Qneat3Framework.py", line 130, in __init__
self.list_tiedPoints = self.director.makeGraph(self.builder, self.list_input_points, self.feedback)
Exception: unknown

Execution failed after 13.84 seconds

Loading resulting layers
Algorithm 'Iso-Area as Polygons (from Layer)' finished

**Comment by root676** [comment]
I close this ticket due to insufficient information on the problem.
