### ISSUE TITLE
I have an OD matrix issue. All result values of OD matrix are output as NULL values.

### ISSUE THREAD

**Issue by minseonee** [root676/QNEAT3#53]
I am currently conducting an experiment related to forest fire research. OD matrix was conducted to measure the distance between the coordinates of forest fires in certain areas of Korea and major tourist destinations. I tried both because I wasn't sure how to proceed between "OD matrix from Layers as Lines" and "OD matrix from Layers as Table."

In the case of **'as Lines'**, the NULL value is output as follows. I'm not sure why, so I don't even know what data to modify.
![as Lines](https://user-images.githubusercontent.com/76714303/153793749-b1faa3b4-086e-4645-811c-37a70efb9a71.png)

In the case of **'as Table'**, it appears that the result shp file could not be generated as follows.
_Get the calculated layer.
The next layer was not properly created.
• D:/odmatrix/2015GangneungTable.shp
To find more information related to algorithm execution, check the 'Log Message Panel' in the QGIS main window._
![as Table](https://user-images.githubusercontent.com/76714303/153793765-d9409672-883f-4658-b549-41518a6aafbe.png)

![image](https://user-images.githubusercontent.com/76714303/153796106-b925cde1-d563-4757-8f02-2aa31773ef45.png)
and this is how i upload and check my files..

I'm eagerly waiting for your help. I will attach the files I put as input files and the corresponding qgis file.
[https://drive.google.com/file/d/118_AruYCrvkOIUVonFC7R9F7yebAagyH/view?usp=sharing](url)

((I wanted to upload files but i couldn't... I'm sorry for uploading the files as url ㅠㅠ))

- Link  : is the road file
- TravelSite : has a shp file that includes travlesites.
- 2015GangneungFire : is a file that includes the information of fire. it is csv file so you have to upload on qgis as EPSG5179 if you need...
- **2015Gangnueng** : is a QGIS file that inlcudes all above files. maybe you can check my problem with this file!

**Comment by matthewmeadows81** [comment]
Ensure each layer has the same EPSG, the point layers are point layers and not multipoint.  Use multipart to single part on the point layers if they are multipoint.
