### ISSUE TITLE
OD Matrix from Layers as Lines (m:n) Nonsensical From and To-layer Locations and Distance Results 

### ISSUE THREAD

**Issue by matthewmeadows81** [root676/QNEAT3#54]
QGIS 3.22.4-Białowieża and QNEAT 1.0.4.

Many of the From and To-layer network locations and distance results in the OD matrix do not make sense.  There are very distant and unreachable locations listed in the OD matrix which causes filtering and selecting the correct minimum From and To total_cost distances impossible.

For example, some of the locations are very distant from the From point, and many are unreachable via the network, but the OD matrix results state it is the minimum amongst all the candidate To points nearby the From point.  However, the closest point is amongst the results, but its distance is between the highest and lowest total_cost values.

The network layer is a stream layer from the Gov. Canada and the From and To-layer points are derived using the line intersections tool in QGIS.

All layers in EPSG 26911 (NAD83 UTM 11N).

I have snapped all points to the closest nodes in the network layer.  I have also checked the topology & geometry and everything seems ok.

Any help or guidance would be greatly appreciated, since I have been looking over and trying to solve this problem for many days. 

Attached are my files. (OD Matrix, From and To-layers, and stream network layer).

Network Layer Note: Water flow direction is compared to the feature digitizing direction --> fldir is the direction field
20 | Not Identified | Unknown, not listed, not applicable or impossible to determine.
32 | Same Direction | The flow direction and the digitizing direction are the same.
33 | Opposite Direction | The flow or event direction and the digitizing direction are opposite.
34 | Not Applicable | Not Applicable
![OD Matrix Parameters](https://user-images.githubusercontent.com/64292014/159979527-6f9d0a37-8e5d-47f4-b153-6c79382b1a3c.png)
[Git Hub.zip](https://github.com/root676/QNEAT3/files/8344159/Git.Hub.zip)

Thank you

**Comment by cvdwilde** [comment]
I am having the same issue. Did you ever find a resolution?

**Comment by josephholler** [comment]
In the streams data, try visualizing the lines with Arrow symbols for each segment in QGIS. You'll see that many of the segments are digitized to flow in the wrong direction, making it impossible to flow to very many road crossings from each pipe crossing. In other GitHub issues, I recall folks observing that ODMatrix could return spurious data if no route was found from an origin to a destination.

**Comment by matthewmeadows81** [comment]
>

**Comment by matthewmeadows81** [comment]
> I ended up learning some sql programming, and used postgis+pgrouting to create a more customizable routing program.  It is both faster and more flexible.
