### ISSUE TITLE
How to not display straight line path in Od matrix from points as lines ( n:n ) ?

### ISSUE THREAD

**Issue by ayush1830** [root676/QNEAT3#56]
While incorparating visualisation present in shortest path ( point to point ) in Od matrix from points as lines ( n:n ), i am getting straight line path as well as the actual path between nodes. How to prevent the straight line path from getting displayed?

**Comment by root676** [comment]
I am not sure if I understand your problem correctly. How are you incorporating the shortest path in the OD matrix? Those are two separate algorithms.

**Comment by ayush1830** [comment]
I have copied some part of the code of shortest path and pasted it in OD
matrix at the appropriate place and I am getting the shortest path route as
well and i do not want the straight line path which is there.
ᐧ

**Comment by root676** [comment]
If you can change the code of QNEAT3 you should also be able to remove the straight lines from the OD matrix. Sorry but I cannot help you with this.
