### ISSUE TITLE
[Feature Request] Allow parallel processing

### ISSUE THREAD

**Issue by ar-siddiqui** [root676/QNEAT3#58]
I am running `OD matrix from Layers as Lines` tool on a big network and it has been over 24 hours and the algorithm is not finished yet. I checked the resources monitor and the CPU is being utlizied below 20%. It would be nice to allow parallel processing to make the overall process faster.

**Comment by root676** [comment]
Unfortunately this is out of scope for the QNEAT3 plugin. It relies heavily on QGIS C++ classes that don't support parallelization. You might want to look into other solutions such as pgrouting on a PostGIS database.
