### ISSUE TITLE
Using the Fastest Path Optimization for Data other than Speed

### ISSUE THREAD

**Issue by alaatorkey95** [root676/QNEAT3#64]
Thank you for this fruitful plugin.

I have an inquiry about the "Fastest Path Optimization" used in OD Matrices in QNEAT 3. 
What if I have used another attribute instead of "Speed" in the "Speed Field"..as if I am trying to use the fastest path optimization to quantify the routes based on another attribute than speed?

How will this affect the calculation of the network cost as well as entry and exit costs?

**Comment by root676** [comment]
You could simply try - but you will end up with bogous values. To achieve routing with other attributes you would have to implement another routing strategy class in python (inheriting from QgsNetworkStrategy). When choosing Speed as strategy, then QNEAT3 uses the [QgsNetworkSpeedStrategy](https://qgis.org/pyqgis/3.28/analysis/QgsNetworkSpeedStrategy.html#qgis.analysis.QgsNetworkSpeedStrategy) which converts speed values into time cost as an output for the plugin. So, using speed strategy with other attributes than speed would apply the transformation to time values, which would not result in meaningful values for the attribute that has been supplied.

**Comment by alaatorkey95** [comment]
Can you please provide a link for the shared code where I can do this?

**Comment by root676** [comment]
I already provided it (see links above). You have to implement the class yourself inheriting from the QgsNetworkStrategy class. There is no tutorial on how to do that.

**Comment by alaatorkey95** [comment]
The links worked now. Thanks alot

**Comment by alaatorkey95** [comment]
Can you please let me know how can I run the whole code of QNEAT3 on QGIS after I have modified it to inherit from other classes?...The thing is that there are multiple .py files connected to each other.

**Comment by alaatorkey95** [comment]
I have modified the QNEAT3 code, precisely the two files titled: "OD Matrix from Layers as Lines (m:n).py" and "Qneat3Framework.py". However, while running on QGIS, I got the following errors:
1-Traceback (most recent call last):
File "C:\.......AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\algs\OdMatrixFromLayersAsLines.py", line 251, in processAlgorithm
net = Qneat3Network(network, merged_coords, strategy, directionFieldName, forwardValue, backwardValue, bothValue, defaultDirection, analysisCrs, speedFieldName, risk_attribute, tolerance, feedback)
File "C:\....../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\Qneat3Framework.py", line 116, in __init__
self.director.addStrategy(self.strategy)
AttributeError: 'Qneat3Network' object has no attribute 'strategy'


2-The entry field inputs for roadway direction donot appear any more.

![image](https://github.com/root676/QNEAT3/assets/78283205/73db8f07-9e5d-4e9d-9b54-3d1a285346c6)
