### ISSUE TITLE
Crash with unknow error when try run shortest path

### ISSUE THREAD

**Issue by FranklinJS** [root676/QNEAT3#9]
Trying run the shortest path algorithm results:

> Processing algorithm…
> Algoritmo 'Shortest path (point to point)' iniciando…
> Entrada de parâmetros:
> { 'DEFAULT_DIRECTION' : 2, 'DEFAULT_SPEED' : 5, 'DIRECTION_FIELD' : None, 'END_POINT' : '326661.9873878573,7954208.542708622 [EPSG:31982]', 'INPUT' : 'LineString?crs=EPSG:31982&field=id:long(10)&field=Descricao:string(80)&field=Tipo:string(100)&field=ID1:long(10)&uid={c5a16068-757f-497e-bf65-aabf90cb7b13}', 'OUTPUT' : 'memory:', 'SPEED_FIELD' : None, 'START_POINT' : '322257.67780760466,7957665.089467809 [EPSG:31982]', 'STRATEGY' : 0, 'TOLERANCE' : 0, 'VALUE_BACKWARD' : '', 'VALUE_BOTH' : '', 'VALUE_FORWARD' : '' }
> 
> [QNEAT3Algorithm] This is a QNEAT3 Algorithm: 'Shortest path (point to point)'
> [QNEAT3Algorithm] Initializing Variables
> [QNEAT3Algorithm] Building Graph
> [QNEAT3Network][__init__] Setting up parameters
> [QNEAT3Network][__init__] Setting up network direction parameters
> [QNEAT3Network][__init__] Setting up analysis points
> [QNEAT3Network][__init__] Setting analysis strategy: 0
> [QNEAT3Network][__init__] Start tying analysis points to the graph and building it.
> [QNEAT3Network][__init__] This is a compute intensive task and may take some time depending on network size
> [QNEAT3Network][__init__] Start Time: :2018-10-09 20:54:29
> [QNEAT3Network][__init__] Building...
> Traceback (most recent call last):
> File "C:/Users/Franklin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\algs\ShortestPathBetweenPoints.py", line 205, in processAlgorithm
> net = Qneat3Network(network, input_qgspointxy_list, strategy, directionFieldName, forwardValue, backwardValue, bothValue, defaultDirection, analysisCrs, speedFieldName, defaultSpeed, tolerance, feedback)
> File "C:/Users/Franklin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QNEAT3\Qneat3Framework.py", line 127, in __init__
> self.list_tiedPoints = self.director.makeGraph(self.builder, self.list_input_points, self.feedback)
> Exception: unknown
> 
> A execução falhou após 0.05 segundos
> 
> Carregando camada resultante
> Algoritmo 'Shortest path (point to point)' finalizado

**Comment by FranklinJS** [comment]
![qgisversion](https://user-images.githubusercontent.com/13770751/46705525-41c37a00-cc06-11e8-98d3-e9ace630fbc6.png)

**Comment by rgnixon** [comment]
Have discovered that the error I'm getting is related to the number of nodes in my network layer. I have had success by 'thinning' a smaller network layer. Will now try to thin the large network layer that I need to use.

**Comment by cormundo** [comment]
I am getting the same error - how can I run QNEAT3 with large complex networks?
